version: "3"
services:
  postgresql:
    build:
      dockerfile: postgresql.dockerfile
      context: ""
    image: jetbov/postgresql
    container_name: banco-aplicacao
    ports:
      - "5432:5432"
    networks:
      - production-network
 
  appjetbov:
    build:
      dockerfile: api.dockerfile
      context: ""
    image: jetbov:latest
    container_name: jetbov
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/docker
      - SPRING_DATASOURCE_USERNAME=docker
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgresql
    ports:
      - "8090:8090"
    networks:
      - production-network

networks:
  production-network:
    driver: bridge